// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package HelloSV

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringM struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringM) Reset()         { *m = StringM{} }
func (m *StringM) String() string { return proto.CompactTextString(m) }
func (*StringM) ProtoMessage()    {}
func (*StringM) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *StringM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringM.Unmarshal(m, b)
}
func (m *StringM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringM.Marshal(b, m, deterministic)
}
func (m *StringM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringM.Merge(m, src)
}
func (m *StringM) XXX_Size() int {
	return xxx_messageInfo_StringM.Size(m)
}
func (m *StringM) XXX_DiscardUnknown() {
	xxx_messageInfo_StringM.DiscardUnknown(m)
}

var xxx_messageInfo_StringM proto.InternalMessageInfo

func (m *StringM) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*StringM)(nil), "HelloSV.StringM")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xf7, 0x00, 0x71, 0x82, 0xc3, 0x94, 0xe4,
	0xb9, 0xd8, 0x83, 0x4b, 0x8a, 0x32, 0xf3, 0xd2, 0x7d, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73,
	0x4a, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0xa3, 0x02, 0x2e, 0x1e, 0x88,
	0xda, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x6d, 0x2e, 0x56, 0x30, 0x5f, 0x48, 0x40, 0x0f,
	0x6a, 0x86, 0x1e, 0xd4, 0x00, 0x29, 0x0c, 0x11, 0x21, 0x63, 0x2e, 0x4e, 0xa7, 0x4c, 0xe7, 0x8c,
	0xc4, 0xbc, 0xbc, 0xd4, 0x1c, 0x62, 0x34, 0x68, 0x30, 0x1a, 0x30, 0x26, 0xb1, 0x81, 0x9d, 0x68,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x64, 0x41, 0xcc, 0x6c, 0xb1, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Hello(ctx context.Context, in *StringM, opts ...grpc.CallOption) (*StringM, error)
	BiChannel(ctx context.Context, opts ...grpc.CallOption) (HelloService_BiChannelClient, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Hello(ctx context.Context, in *StringM, opts ...grpc.CallOption) (*StringM, error) {
	out := new(StringM)
	err := c.cc.Invoke(ctx, "/HelloSV.HelloService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) BiChannel(ctx context.Context, opts ...grpc.CallOption) (HelloService_BiChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloService_serviceDesc.Streams[0], "/HelloSV.HelloService/BiChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceBiChannelClient{stream}
	return x, nil
}

type HelloService_BiChannelClient interface {
	Send(*StringM) error
	Recv() (*StringM, error)
	grpc.ClientStream
}

type helloServiceBiChannelClient struct {
	grpc.ClientStream
}

func (x *helloServiceBiChannelClient) Send(m *StringM) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceBiChannelClient) Recv() (*StringM, error) {
	m := new(StringM)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Hello(context.Context, *StringM) (*StringM, error)
	BiChannel(HelloService_BiChannelServer) error
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) Hello(ctx context.Context, req *StringM) (*StringM, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedHelloServiceServer) BiChannel(srv HelloService_BiChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method BiChannel not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringM)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloSV.HelloService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Hello(ctx, req.(*StringM))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_BiChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).BiChannel(&helloServiceBiChannelServer{stream})
}

type HelloService_BiChannelServer interface {
	Send(*StringM) error
	Recv() (*StringM, error)
	grpc.ServerStream
}

type helloServiceBiChannelServer struct {
	grpc.ServerStream
}

func (x *helloServiceBiChannelServer) Send(m *StringM) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceBiChannelServer) Recv() (*StringM, error) {
	m := new(StringM)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HelloSV.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloService_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BiChannel",
			Handler:       _HelloService_BiChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}
